// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using StormSafe.Infrastructure.Contexts;

#nullable disable

namespace StormSafe.Migrations
{
    [DbContext(typeof(StormSafeDbContext))]
    partial class StormSafeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StormSafe.Infrastructure.Persistence.Rio", b =>
                {
                    b.Property<int>("RioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_rio");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RioId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.HasKey("RioId");

                    b.ToTable("TBL_RIOS", (string)null);
                });

            modelBuilder.Entity("StormSafe.Infrastructure.Persistence.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_sensor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<int>("RioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_rio");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("tipo");

                    b.HasKey("SensorId");

                    b.HasIndex("RioId");

                    b.ToTable("TBL_SENSORES", (string)null);
                });

            modelBuilder.Entity("StormSafe.Infrastructure.Persistence.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("senha");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("role");

                    b.HasKey("IdUsuario");

                    b.ToTable("TBL_USUARIOS", (string)null);
                });

            modelBuilder.Entity("StormSafe.Infrastructure.Persistence.Sensor", b =>
                {
                    b.HasOne("StormSafe.Infrastructure.Persistence.Rio", "Rio")
                        .WithMany("Sensores")
                        .HasForeignKey("RioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rio");
                });

            modelBuilder.Entity("StormSafe.Infrastructure.Persistence.Rio", b =>
                {
                    b.Navigation("Sensores");
                });
#pragma warning restore 612, 618
        }
    }
}
